"""
Commander AI Lab — Politics Comms Channel (Phase 6)
====================================================
Handles the spoken / narrated side of the politics system:
  - ThreatBroadcast: a seat declaring its intentions publicly
  - PoliticsCommsChannel: message bus that routes broadcasts to
    other seats and to the narration panel

AI personas use this to say things like:
  "Timmy: Anyone who attacks me this turn is getting Craterhoof next turn."
  "Spike: I'll leave P2 alone if someone deals with that Seedborn Muse."
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Callable, Awaitable, Optional


class BroadcastType(Enum):
    THREAT        = auto()   # "If you X, I will Y"
    OFFER         = auto()   # "I will X if you Y"
    WARNING       = auto()   # "I am about to X"
    TAUNT         = auto()   # flavour / personality expression
    GRATITUDE     = auto()   # acknowledging help
    ACCUSATION    = auto()   # calling out a deal-breaker
    CALL_TO_ARMS  = auto()   # urging others to attack a seat


@dataclass
class ThreatBroadcast:
    """
    A public statement from one seat addressed to one or all seats.

    Attributes:
        speaker:      Seat index sending the message.
        audience:     Seat index of intended recipient (-1 = table).
        broadcast_type: Flavour category.
        text:         Natural-language text (generated by AI persona).
        turn:         Game turn when spoken.
        condition_seat: The seat the statement is about (if any).
    """
    speaker:          int
    audience:         int          # -1 = everyone
    broadcast_type:   BroadcastType
    text:             str
    turn:             int
    condition_seat:   Optional[int] = None


# Callback type: async function that receives a ThreatBroadcast
BroadcastHandler = Callable[[ThreatBroadcast], Awaitable[None]]


class PoliticsCommsChannel:
    """
    Message bus for politics broadcasts.

    Handlers can be registered per-seat (AI opponents) or globally
    (narration panel, WebSocket broadcast).

    Usage::

        channel = PoliticsCommsChannel()
        channel.register_handler(seat=1, handler=ai_timmy.on_broadcast)
        channel.register_global_handler(narration_panel.on_broadcast)

        await channel.broadcast(ThreatBroadcast(
            speaker=0, audience=-1,
            broadcast_type=BroadcastType.CALL_TO_ARMS,
            text="Focus Spike! He has a combo!",
            turn=4, condition_seat=2,
        ))
    """

    def __init__(self) -> None:
        self._seat_handlers:   dict[int, list[BroadcastHandler]] = {}
        self._global_handlers: list[BroadcastHandler] = []
        self._log: list[ThreatBroadcast] = []

    def register_handler(
        self,
        seat: int,
        handler: BroadcastHandler,
    ) -> None:
        """Register a handler that receives broadcasts addressed to `seat`."""
        self._seat_handlers.setdefault(seat, []).append(handler)

    def register_global_handler(
        self,
        handler: BroadcastHandler,
    ) -> None:
        """Register a handler that receives ALL broadcasts."""
        self._global_handlers.append(handler)

    async def broadcast(
        self,
        msg: ThreatBroadcast,
    ) -> None:
        """
        Dispatch a broadcast to all relevant handlers.
        Global handlers always fire. Seat handlers fire if audience matches
        or if the broadcast is to the whole table (audience == -1).
        """
        self._log.append(msg)

        for handler in self._global_handlers:
            await handler(msg)

        if msg.audience == -1:
            # Broadcast to all seats except speaker
            for seat, handlers in self._seat_handlers.items():
                if seat == msg.speaker:
                    continue
                for h in handlers:
                    await h(msg)
        else:
            for h in self._seat_handlers.get(msg.audience, []):
                await h(msg)

    def recent_broadcasts(
        self,
        last_n: int = 10,
        speaker: Optional[int] = None,
        audience: Optional[int] = None,
    ) -> list[ThreatBroadcast]:
        """Return the last N broadcasts, optionally filtered."""
        results = [
            b for b in self._log
            if (speaker  is None or b.speaker  == speaker)
            and (audience is None or b.audience == audience or b.audience == -1)
        ]
        return results[-last_n:]

    def clear(self) -> None:
        self._log.clear()
